### ISSUE TITLE
IS there a way to keep a google cloud shell active?

### ISSUE THREAD

**Issue by lordofwizard** [tobigithub/cloud-computing#7]
Hello is there a way to keep a gcloud shell active and keep it from disconnecting after 20 minutes? please?

**Comment by tobigithub** [comment]
@lordofwizard good question, I actually had it open for a couple of hours,
but according to the documentation it is limited to 12h.
https://cloud.google.com/shell/docs/limitations
specifically
https://cloud.google.com/shell/docs/limitations#usage_limits

So what you can do is to open the cheapest micro instance and then work from there.
They will never disconnect, I have some of them open since a couple of weeks.
